# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HelloActivity' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HelloActivity

  pod 'SDWebImageSwiftUI'
  pod 'Alamofire'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'GoogleSignIn'
  pod 'GoogleSignInSwiftSupport'
  pod 'LineSDKSwift', '~> 5.0'
  pod 'R.swift'
end
